# Generated by Django 4.2.7 on 2023-11-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0006_itemsonbid_hours_itemsonbid_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemsonbid",
            name="wallet_addr",
            field=models.CharField(default="0x0", max_length=42),
        ),
    ]
