# Generated by Django 4.2.7 on 2023-11-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_itemsonbid_wallet_addr"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemsonbid",
            name="wallet_addr",
        ),
        migrations.AddField(
            model_name="itemsclaimed",
            name="highest_bid",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="itemsclaimed",
            name="highest_bidder_username",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="users",
            name="wallet_addr",
            field=models.CharField(default="0x0", max_length=42),
        ),
    ]
